### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by laurar9889** [danielmolina81/FinalProject#1]
- [x] Data Collection @Mohammed-a-ali01 @danielmolina81 target date: Tuesday Aug 06
- [x] SQL - ETL @laurar9889 target date: Wednesday Aug 07
- [x] Data Cleaning @Mohammed-a-ali01 target date: Wednesday Aug 07
- [x] Visualizations on Tableau @JelenaRaonic  target date: Monday Aug 12
- [x] Model coding @Mohammed-a-ali01 @danielmolina81 @JelenaRaonic @laurar9889 target date: Monday Aug 12
- [ ] Final touches target date: Monday Aug 12
- [x] Slides @laurar9889 target date: Wednesday Aug 14
